/icp_registration:
  ros__parameters:
    use_sim_time: false 
    rough_leaf_size: 0.4
    refine_leaf_size: 0.1
    # pcd_path: "src/rm_nav_bringup/pcd/2.pcd" 
    # pcd_path: "src/rm_nav_bringup/pcd/b.pcd" 
    # pcd_path: "src/rm_nav_bringup/pcd/b1.pcd" 
    pcd_path: "src/rm_nav_bringup/pcd/homer.pcd" 
    map_frame_id: "map"
    odom_frame_id: "odom"
    laser_frame_id: "base_link"
    pointcloud_topic: "/cloud_registered"
    thresh: 0.1
    xy_offset: 0.1
    yaw_offset: 30.0
    yaw_resolution: 10.0
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw
    # initial_pose: [20.75, -1.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw