<?xml version="1.0"?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="length" value="0.12" />
    <xacro:property name="radius" value="0.1" />

     <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0 0 0" />
    </joint>

    <link name="base_link">
            <visual>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${length}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${length}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </collision>
            <inertial>
                <mass value="1.0" />
                <inertia ixx="${(1.0/12) * (3*0.1*0.1 + 0.12*0.12)}" ixy="0" ixz="0" iyy="${(1.0/12) * (3*0.1*0.1 + 0.12*0.12)}" iyz="0" izz="${(1.0/2) * (0.1*0.1)}" />
            </inertial>
    </link>

    <!-- 主动轮 -->
    <link name="left_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.57079 0 0" />
                <geometry>
                    <cylinder length="0.04" radius="0.032" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.57079 0 0" />
                <geometry>
                    <cylinder length="0.04" radius="0.032" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </collision>
            <inertial>
                <mass value="0.1" />
                <inertia ixx="${(0.1/12) * (3*0.032*0.032 + 0.04*0.04)}" ixy="0" ixz="0" iyy="${(0.1/12) * (3*0.032*0.032 + 0.04*0.04)}" iyz="0" izz="${(0.1/2) * (0.032*0.032)}" />
            </inertial>
    </link>
    <gazebo reference="left_wheel_link">
            <mu1 value="20.0" />
            <mu2 value="20.0" />
            <kp value="1000000000.0" />
            <kd value="1.0" />
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="left_wheel_link" />
            <origin xyz="0 0.10 -0.06" />
            <axis xyz="0 1 0" />
    </joint>

    <link name="right_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="1.57079 0 0" />
                <geometry>
                    <cylinder length="0.04" radius="0.032" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.57079 0 0" />
                <geometry>
                    <cylinder length="0.04" radius="0.032" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </collision>
            <inertial>
                <mass value="0.1" />
                <inertia ixx="${(0.1/12) * (3*0.032*0.032 + 0.04*0.04)}" ixy="0" ixz="0" iyy="${(0.1/12) * (3*0.032*0.032 + 0.04*0.04)}" iyz="0" izz="${(0.1/2) * (0.032*0.032)}" />
            </inertial>
    </link>
    <gazebo reference="right_wheel_link">
            <mu1 value="20.0" />
            <mu2 value="20.0" />
            <kp value="1000000000.0" />
            <kd value="1.0" />
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="right_wheel_link" />
            <origin xyz="0 -0.10 -0.06" />
            <axis xyz="0 1 0" />
    </joint>
    
    <!-- 从动轮 -->
    <link name="front_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.016" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.016" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </collision>
            <inertial>
                <mass value="0.01" />
                <inertia ixx="${(2/5) * 0.01 * (0.016*0.016)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * 0.01 * (0.016*0.016)}" iyz="0.0" izz="${(2/5) * 0.01 * (0.016*0.016)}" />
            </inertial>
    </link>
    <gazebo reference="front_caster_link">
            <mu1 value="0.0" />
            <mu2 value="0.0" />
            <kp value="1000000000.0" />
            <kd value="1.0" />
    </gazebo>

    <joint name="front_caster_joint" type="fixed">
            <parent link="base_link" />
            <child link="front_caster_link" />
            <origin xyz="0.08 0.0 -0.076" />
            <axis xyz="0 0 0" />
    </joint>

    <link name="back_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.016" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.016" />
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 0.8"/>
                </material>
            </collision>
            <inertial>
                <mass value="0.01" />
                <inertia ixx="${(2/5) * 0.01 * (0.016*0.016)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * 0.01 * (0.016*0.016)}" iyz="0.0" izz="${(2/5) * 0.01 * (0.016*0.016)}" />
            </inertial>
    </link>
    <gazebo reference="back_caster_link">
            <mu1 value="0.0" />
            <mu2 value="0.0" />
            <kp value="1000000000.0" />
            <kd value="1.0" />
    </gazebo>

    <joint name="back_caster_joint" type="fixed">
            <parent link="base_link" />
            <child link="back_caster_link" />
            <origin xyz="-0.08 0.0 -0.076" />
            <axis xyz="0 0 0" />
    </joint>

    <gazebo>
            <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
                <ros>
                    <namespace>/</namespace>
                    <remapping>cmd_vel:=cmd_vel</remapping>
                    <remapping>odom:=odom</remapping>
                </ros>
                <update_rate>30</update_rate>
                <!-- wheels -->
                <left_joint>left_wheel_joint</left_joint>
                <right_joint>right_wheel_joint</right_joint>
                <!-- kinematics -->
                <wheel_separation>0.2</wheel_separation>
                <wheel_diameter>0.064</wheel_diameter>
                <!-- limits -->
                <max_wheel_torque>20</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>
                <!-- output -->
                <publish_odom>false</publish_odom>
                <publish_odom_tf>false</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>

                <odometry_frame>odom</odometry_frame>
                <robot_base_frame>base_footprint</robot_base_frame>
            </plugin>
    </gazebo>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="front_caster_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="back_caster_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- IMU -->
    <link name="imu_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
        </visual>

        <inertial>
            <mass value="1e-2" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <joint name="imu_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0.0 0 0.08" rpy="0 0 0"/> <!-- 再向前移动3厘米 -->
        <parent link="base_link"/>
        <child link="imu_link"/>
    </joint>

    <gazebo reference="imu_link">
        <material>Gazebo/Orange</material>
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <topic>__default_topic__</topic>
            <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
                <topicName>/livox/imu</topicName>
                <bodyName>imu_link</bodyName>
                <updateRateHZ>100.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
                <frameName>imu_link</frameName>
                <serviceName>default_service</serviceName>
                <alwaysOn>true</alwaysOn>
                <maxAngularVelocity>100.0</maxAngularVelocity>
                <noiseDensity>0.0</noiseDensity>
                <randomWalk>0.0</randomWalk>
                <ros>
                    <remapping>~/out:=/livox/imu</remapping>
                </ros>
            </plugin>
        </sensor>
    </gazebo>

    <!-- Livox-Mid360  -->
    <xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro" />
    <xacro:mid360 name="livox_frame" parent="base_link" topic="/livox/lidar">
        <origin xyz="0.0 0.0 0.13" rpy="0 0 0"/>
    </xacro:mid360>
</robot>
