/**:
    ros__parameters:
        common:
            lid_topic:  "/merged_custom" 
            # lid_topic:  "/livox/lidar_192_168_1_125" 
            imu_topic:  "/imu/data"  #from imu_complementary_filter
            # imu_topic:  "/livox/imu_192_168_1_125" 
            # imu_topic:  "/livox/imu1" 
            con_frame: false # true: if you need to combine several LiDAR frames into one
            con_frame_num: 1 # the number of frames combined
            cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
            cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency
            time_lag_imu_to_lidar: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)
                                    # the timesample of IMU is transferred from the current timeline to LiDAR's timeline by subtracting this value
            

        preprocess:
            lidar_type: 1  
            scan_line: 4
            scan_rate: 10
            timestamp_unit: 3           
            blind: 0.35 

        mapping:
            imu_en: true
            start_in_aggressive_motion: false 
            extrinsic_est_en: false 
            imu_time_inte: 0.005 
            satu_acc: 3.0 
            satu_gyro: 35.
            acc_norm: 1.0
            lidar_meas_cov: 0.001
            acc_cov_output: 500.
            gyr_cov_output: 1000. 
            b_acc_cov: 0.0001 
            b_gyr_cov: 0.0001 
            imu_meas_acc_cov: 0.1
            imu_meas_omg_cov: 0.1
            gyr_cov_input: 0.01 
            acc_cov_input: 0.1 
            plane_thr: 0.1 
            match_s: 81.0
            fov_degree: 360. 
            det_range: 450.0
            gravity_align: false 
            gravity: [-0.0, -0.01, -0.9810] 
            gravity_init: [-0.0, -0.01, -0.9810]  
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            # extrinsic_T: [ 0.0, 0.0, 0.0] # Lidar相对于IMU的平移矩阵
            extrinsic_R: [  1., 0., 0.,
                            0., 1., 0.,
                            0., 0., 1.]    
        odometry: 
            publish_odometry_without_downsample: false
        publish:
            path_en: true                 
            scan_publish_en: true         
            scan_bodyframe_pub_en: true  

        pcd_save:
            use_pcd_map_: false 
            # prior_PCD_map_truepath: "src/rm_nav_bringup/pcd/transformed_cloud1.pcd" 
            # prior_PCD_map_path: "src/rm_nav_bringup/pcd/8.pcd" 
            # prior_PCD_map_path: "src/rm_nav_bringup/pcd/b1.pcd" 
            prior_PCD_map_path: "src/rm_nav_bringup/pcd/homer.pcd" 
            pcd_save_en: true
            interval: -1                  
        init_pos:
            # init_x: 6.0
            # init_y: -0.3
            # init_z: 0.0
            # init_x: 0.0
            # init_y: 0.0
            # init_z: 0.0
            init_x: 0.0
            init_y: 0.0
            init_z: 0.0
        gcl:
            task: "B"

        # init_pos:
        #     # init_x: 6.0
        #     # init_y: -0.3
        #     # init_z: 0.0
        #     # init_x: 0.0
        #     # init_y: 0.0
        #     # init_z: 0.0
        #     init_x: 13.21
        #     init_y: -1.11
        #     init_z: 0.0
        # gcl:
        #     task: "A"
